pool:
  vmImage: ubuntu-latest

steps:

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build jacocoTestReport'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: 'Construir aplicaci칩n'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
        **/build/libs/*.jar
        **/build/**/*.xml
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Preparar artefacto'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: appJar
    publishLocation: 'Container'
  displayName: 'Publicar artefacto'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'appJar'
    downloadPath: '$(Pipeline.Workspace)'
  displayName: 'Artefacto para Sonar'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar-cloud-usach'
    organization: 'cl-usach-diplomados-rolivares'
    projectKey: 'devops-foundation-ms'
    projectName: 'devops-foundation-ms'
    extraProperties: |
      sonar.coverage.jacoco.xmlReportPaths=$(Pipeline.Workspace)/appJar/build/reports/jacoco/test/jacocoTestReport.xml
  displayName: 'Configurar Sonarqube'
    
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: "build jacocoTestReport"
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
  displayName: 'An치lisis de c칩digo'
    
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publicando resultados sonar'
  
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'appJar'
    downloadPath: '$(Pipeline.Workspace)'
  displayName: Descarga Jar
- script: "mkdir -p build/libs; mv $(Pipeline.Workspace)/appJar/build/libs/ build/; chmod -R 555 build/libs"  
  displayName:  'Preparando aplicaci칩n para Docker'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub-usach'
    command: 'login'
  displayName: Autenticando Docker Registry
    
- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub-usach'
    repository: 'tarea1'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: latest
  displayName: 'Construyendo imagen'