pool: 'Default'

steps:

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build jacocoTestReport'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
  displayName: 'Build Plugin'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
        **/build/libs/*.jar
        **/build/**/*.xml
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: appJar
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'appJar'
    downloadPath: '$(Pipeline.Workspace)'
  displayName: Descarga Jar
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar-cloud-usach'
    organization: 'cl-usach-diplomados-rolivares'
    projectKey: 'devops-foundation-ms'
    projectName: 'devops-foundation-ms'
    extraProperties: |
      sonar.coverage.jacoco.xmlReportPaths=$(Pipeline.Workspace)/appJar/build/reports/jacoco/test/jacocoTestReport.xml
  displayName: 'Preparing Sonarqube Environment'
    
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: "build jacocoTestReport"
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
  displayName: 'Analyze current Branch'
    
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Analysis Results'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'appJar'
    downloadPath: '$(Pipeline.Workspace)'
  displayName: Descarga Jar
- script: "dir"   
#- script: "mkdir -p build/libs; mv $(Pipeline.Workspace)/appJar/build/libs/ build/; chmod -R 555 build/libs"  
#- script: "mkdir -p build\\libs; mv $(Pipeline.Workspace)\\appJar\\build\\libs\\ build\\"
  displayName:  Se mueve JAR a carpeta raiz

- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub-usach'
    command: 'login'
  displayName: Docker registry login
    
- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub-usach'
    repository: 'tarea1'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: latest
  displayName: Build Image